backend:
  name: github
  repo: brootaylor/uxbrighton # Path to the GitHub code repository
  branch: gh-pages # Branch that Netlify CMS will be available on
  site_domain: netlify-cms-hookup.netlify.com # Using a placeholder Netlify site and custom Netlify domain to enable the backend OAuth configuration

# These lines should *not* be indented
publish_mode: editorial_workflow # Ensures content goes through workflow first, ("Drafts" --> "In Review" --> "Ready"), before being published
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "images/uploads" # The src attribute for uploaded media will begin with images/uploads
site_url: https://brootaylor.github.io/uxbrighton/
display_url: https://brootaylor.github.io/uxbrighton/
logo_url: https://brootaylor.github.io/uxbrighton/2022/logo/red-square-2018.png

collections:
  - name: "homepages" # Used in routes, e.g., /admin/collections/blog
    label: "Homepages" # Used in the UI
    files:
      - label: "Homepage {{year}}"
        name: "homepage"
        file: "{{year}}/index.html"
        fields: # The fields for each document, usually in front matter
          - {label: "Title", name: "title", widget: "string"}