backend:
  name: github
  repo: brootaylor/uxbrighton # Path to the GitHub code repository
  branch: gh-pages # Branch that Netlify CMS will be available on
  site_domain: netlify-cms-hookup.netlify.com # Using a placeholder Netlify site and custom Netlify domain to enable the backend OAuth configuration

# These lines should *not* be indented
publish_mode: editorial_workflow # Ensures content goes through workflow first, ("Drafts" --> "In Review" --> "Ready"), before being published
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "images/uploads" # The src attribute for uploaded media will begin with images/uploads
site_url: https://brootaylor.github.io/uxbrighton/
display_url: https://brootaylor.github.io/uxbrighton/
logo_url: https://brootaylor.github.io/uxbrighton/2022/logo/red-square-small.png

collections:
  - label: "UX Brighton 2022" # 2022
    name: "uxbri-2022"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "2022/index.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", description: "This is meta content.", widget: "string"}
          - label: "Hero"
            name: "hero"
            widget: "object"
            collapsed: false
            fields:
              - {label: "Button visibility", name: "ticket-button", widget: "select", options: ["show", "hide"], default: ["show"]}
              - {label: "Button text", name: "ticket-button-text", widget: "string"}
              - {label: "Button text (extra)", name: "ticket-button-extra-text", widget: "string"}
              - {label: "Button URL Address", name: "ticket-button-url", widget: "string"}
