backend:
  name: github
  repo: brootaylor/uxbrighton # Path to the GitHub code repository
  branch: gh-pages # Branch that Netlify CMS will be available on
  site_domain: netlify-cms-hookup.netlify.com # Using a placeholder Netlify site and custom Netlify domain to enable the backend OAuth configuration

# These lines should *not* be indented
publish_mode: editorial_workflow # Ensures content goes through workflow first, ("Drafts" --> "In Review" --> "Ready"), before being published
media_folder: "images/uploads"
site_url: https://brootaylor.github.io/uxbrighton/
display_url: https://brootaylor.github.io/uxbrighton/

collections:
  - name: "homepages" # Used in routes, e.g., /admin/collections/blog
    label: "Homepages" # Used in the UI
    folder: "{{year}}" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}